# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: 'src'
    verbose: false
    customCommand: "install --force"

- task: Npm@1
  displayName: 'npm serve'
  inputs:
    command: custom
    workingDir: 'src'
    verbose: false
    customCommand: "install -g serve"
    
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: 'src'
    verbose: false
    customCommand: "run build"

- task: ArchiveFiles@2
  displayName: 'Archive react-app'
  inputs:
    rootFolderOrFile: "src/build"
    includeRootFolder: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'