//Interfaces
export interface RoomDetail {
    id: number;
    idHotel: number;
    name: string;
    price: string;
    image: string;
    status: boolean;
    packagesIncluded: {
        name: string;
        icon: string;
    }[];
}

//Data
export const roomDetailData: RoomDetail[] = [

    {
        id: 1,
        idHotel: 1,
        name: 'Habitación Suite',
        price: 'COP 250.682',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 2,
        idHotel: 1,
        name: 'Habitación Preferencial',
        price: 'COP 300.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "3 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 3,
        idHotel: 1,
        name: 'Habitación Sencilla',
        price: 'COP 240.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 4,
        idHotel: 2,
        name: 'Habitación de Lujo',
        price: 'COP 350.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 2", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 5,
        idHotel: 2,
        name: 'Suite Ejecutiva',
        price: 'COP 450.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 2", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 6,
        idHotel: 2,
        name: 'Habitación Estándar',
        price: 'COP 250.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 7,
        idHotel: 3,
        name: 'Habitación Deluxe',
        price: 'COP 320.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "3 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 8,
        idHotel: 3,
        name: 'Habitación Estándar',
        price: 'COP 280.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 9,
        idHotel: 3,
        name: 'Suite Ejecutiva',
        price: 'COP 400.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 10,
        idHotel: 4,
        name: 'Habitación Vista al Mar',
        price: 'COP 450.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 11,
        idHotel: 4,
        name: 'Suite de Lujo',
        price: 'COP 600.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 1", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 12,
        idHotel: 4,
        name: 'Habitación Estándar',
        price: 'COP 350.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 13,
        idHotel: 5,
        name: 'Suite Colonial',
        price: 'COP 480.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 14,
        idHotel: 5,
        name: 'Habitación Deluxe',
        price: 'COP 350.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 15,
        idHotel: 5,
        name: 'Habitación Estándar',
        price: 'COP 280.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 16,
        idHotel: 6,
        name: 'Suite Ejecutiva',
        price: 'COP 320.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 17,
        idHotel: 6,
        name: 'Habitación Deluxe',
        price: 'COP 280.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 1", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 18,
        idHotel: 6,
        name: 'Habitación Estándar',
        price: 'COP 250.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 19,
        idHotel: 7,
        name: 'Habitación de Lujo',
        price: 'COP 320.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 20,
        idHotel: 7,
        name: 'Suite Ejecutiva',
        price: 'COP 450.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 21,
        idHotel: 7,
        name: 'Habitación Estándar',
        price: 'COP 280.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 1", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 22,
        idHotel: 8,
        name: 'Suite Ejecutiva',
        price: 'COP 400.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 23,
        idHotel: 8,
        name: 'Habitación Estándar',
        price: 'COP 320.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 24,
        idHotel: 8,
        name: 'Habitación Familiar',
        price: 'COP 450.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 25,
        idHotel: 9,
        name: 'Suite Familiar',
        price: 'COP 500.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 26,
        idHotel: 9,
        name: 'Habitación Doble',
        price: 'COP 280.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 27,
        idHotel: 9,
        name: 'Habitación Suite',
        price: 'COP 350.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "1 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 28,
        idHotel: 10,
        name: 'Suite Ejecutiva',
        price: 'COP 450.000',
        image: 'room-suite.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 29,
        idHotel: 10,
        name: 'Habitación Doble',
        price: 'COP 300.000',
        image: 'room-preferencial.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 3", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
    {
        id: 30,
        idHotel: 10,
        name: 'Habitación Estándar',
        price: 'COP 250.000',
        image: 'room-sencilla.jpg',
        status: true,
        packagesIncluded: [
            { name: "Capacidad para 4", icon: 'FaUsers' },
            { name: "Desayuno buffet", icon: 'FaUtensils' },
            { name: "WiFi", icon: 'FaWifi' },
            { name: "Parqueadero", icon: 'FaCar' },
            { name: "2 camas", icon: 'FaBed' },
        ],
    },
]